// ─────────────────────────────────────────────────────────────────────────────
//  DATA.JS — Complete Garment Industry Chinese Vocabulary
//  Categories: Fabric Types, Garment Parts, Operations, Quality Control,
//              Factory Roles, Equipment, Colors/Sizes, Workplace Phrases
// ─────────────────────────────────────────────────────────────────────────────

const CATEGORIES = [
  { id: "fabric",     name: "Fabrics & Materials",     emoji: "🧶", color: "#a855f7" },
  { id: "parts",      name: "Garment Parts",           emoji: "👕", color: "#7c6aff" },
  { id: "operations", name: "Operations & Processes",  emoji: "⚙️", color: "#06d6a0" },
  { id: "qc",         name: "Quality Control",         emoji: "🔍", color: "#ffd166" },
  { id: "equipment",  name: "Equipment & Tools",       emoji: "🧵", color: "#ff6b6b" },
  { id: "roles",      name: "People & Roles",          emoji: "👷", color: "#4ecdc4" },
  { id: "garments",   name: "Garment Types",           emoji: "👗", color: "#ff9f43" },
  { id: "sizes",      name: "Sizes, Colors & Specs",   emoji: "📏", color: "#48dbfb" },
  { id: "factory",    name: "Factory & Production",    emoji: "🏭", color: "#ff6b9d" },
  { id: "workplace",  name: "Workplace Survival",      emoji: "💬", color: "#c7ecee" },
];

const VOCABULARY = [
  // ─────────────────────────────────────────────────────
  //  FABRICS & MATERIALS
  // ─────────────────────────────────────────────────────
  { id: 1,  cat: "fabric", cn: "面料", py: "miànliào",     en: "Fabric / Material",
    example: { cn: "这件衣服的面料是棉。", py: "Zhè jiàn yīfu de miànliào shì mián.", en: "The fabric of this garment is cotton." }},
  { id: 2,  cat: "fabric", cn: "棉",   py: "mián",         en: "Cotton",
    example: { cn: "棉面料透气性好。", py: "Mián miànliào tòuqì xìng hǎo.", en: "Cotton fabric has good breathability." }},
  { id: 3,  cat: "fabric", cn: "涤纶", py: "dílún",        en: "Polyester",
    example: { cn: "这批货是涤纶的。", py: "Zhè pī huò shì dílún de.", en: "This batch of goods is polyester." }},
  { id: 4,  cat: "fabric", cn: "丝绸", py: "sīchóu",       en: "Silk",
    example: { cn: "丝绸面料容易皱。", py: "Sīchóu miànliào róngyì zhòu.", en: "Silk fabric wrinkles easily." }},
  { id: 5,  cat: "fabric", cn: "羊毛", py: "yángmáo",      en: "Wool",
    example: { cn: "这是纯羊毛的吗？", py: "Zhè shì chún yángmáo de ma?", en: "Is this pure wool?" }},
  { id: 6,  cat: "fabric", cn: "氨纶", py: "ānlún",        en: "Spandex / Elastane",
    example: { cn: "加了氨纶，弹性更好。", py: "Jiāle ānlún, tánxìng gèng hǎo.", en: "Adding spandex gives better elasticity." }},
  { id: 7,  cat: "fabric", cn: "尼龙", py: "nílóng",       en: "Nylon",
    example: { cn: "尼龙很耐磨。", py: "Nílóng hěn nài mó.", en: "Nylon is very wear-resistant." }},
  { id: 8,  cat: "fabric", cn: "亚麻", py: "yàmá",         en: "Linen",
    example: { cn: "亚麻面料透气但容易皱。", py: "Yàmá miànliào tòuqì dàn róngyì zhòu.", en: "Linen is breathable but wrinkles easily." }},
  { id: 9,  cat: "fabric", cn: "牛仔布", py: "niúzǎi bù",  en: "Denim",
    example: { cn: "这批牛仔布很厚实。", py: "Zhè pī niúzǎi bù hěn hòu shi.", en: "This batch of denim is very thick." }},
  { id: 10, cat: "fabric", cn: "针织布", py: "zhēnzhī bù", en: "Knit Fabric",
    example: { cn: "针织布有弹性。", py: "Zhēnzhī bù yǒu tánxìng.", en: "Knit fabric has elasticity." }},
  { id: 11, cat: "fabric", cn: "梭织布", py: "suōzhī bù",  en: "Woven Fabric",
    example: { cn: "这是梭织面料。", py: "Zhè shì suōzhī miànliào.", en: "This is woven fabric." }},
  { id: 12, cat: "fabric", cn: "天鹅绒", py: "tiān'é róng", en: "Velvet",
    example: { cn: "天鹅绒面料很柔软。", py: "Tiān'é róng miànliào hěn róuruǎn.", en: "Velvet fabric is very soft." }},
  { id: 13, cat: "fabric", cn: "雪纺",  py: "xuěfǎng",     en: "Chiffon",
    example: { cn: "雪纺很轻薄。", py: "Xuěfǎng hěn qīng bó.", en: "Chiffon is very light and thin." }},
  { id: 14, cat: "fabric", cn: "麻",    py: "má",           en: "Hemp",
    example: { cn: "纯麻很耐用。", py: "Chún má hěn nài yòng.", en: "Pure hemp is very durable." }},
  { id: 15, cat: "fabric", cn: "混纺",  py: "hùnfǎng",     en: "Blended / Mixed Fabric",
    example: { cn: "这是棉涤混纺。", py: "Zhè shì mián dí hùnfǎng.", en: "This is a cotton-polyester blend." }},
  { id: 16, cat: "fabric", cn: "弹力布", py: "tánlì bù",   en: "Stretch Fabric",
    example: { cn: "弹力布适合运动服。", py: "Tánlì bù shìhé yùndòngfú.", en: "Stretch fabric is suitable for sportswear." }},
  { id: 17, cat: "fabric", cn: "格子布", py: "gézǐ bù",    en: "Check / Plaid Fabric",
    example: { cn: "格子布要对格裁剪。", py: "Gézǐ bù yào duì gé cáijiǎn.", en: "Plaid fabric must be aligned when cutting." }},
  { id: 18, cat: "fabric", cn: "条纹布", py: "tiáowén bù", en: "Striped Fabric",
    example: { cn: "条纹布要对条。", py: "Tiáowén bù yào duì tiáo.", en: "Striped fabric must be stripe-matched." }},
  { id: 19, cat: "fabric", cn: "里布",  py: "lǐ bù",       en: "Lining Fabric",
    example: { cn: "这款用哪种里布？", py: "Zhè kuǎn yòng nǎ zhǒng lǐ bù?", en: "Which lining does this style use?" }},
  { id: 20, cat: "fabric", cn: "衬布",  py: "chèn bù",     en: "Interfacing / Interlining",
    example: { cn: "领子要粘衬布。", py: "Lǐngzi yào zhān chèn bù.", en: "The collar needs interfacing." }},
  { id: 21, cat: "fabric", cn: "无纺布", py: "wúfǎng bù",  en: "Non-woven Fabric",
    example: { cn: "这是无纺布衬。", py: "Zhè shì wúfǎng bù chèn.", en: "This is a non-woven interlining." }},
  { id: 22, cat: "fabric", cn: "皮革",  py: "pígé",        en: "Leather",
    example: { cn: "真皮还是人造皮革？", py: "Zhēn pí háishì rénzào pígé?", en: "Real leather or synthetic leather?" }},

  // ─────────────────────────────────────────────────────
  //  GARMENT PARTS
  // ─────────────────────────────────────────────────────
  { id: 23, cat: "parts", cn: "领子",   py: "lǐngzi",      en: "Collar",
    example: { cn: "领子要烫平。", py: "Lǐngzi yào tàng píng.", en: "The collar needs to be ironed flat." }},
  { id: 24, cat: "parts", cn: "领座",   py: "lǐngzuò",     en: "Collar Stand / Band",
    example: { cn: "领座高度是3.5cm。", py: "Lǐngzuò gāodù shì 3.5 cm.", en: "The collar stand height is 3.5cm." }},
  { id: 25, cat: "parts", cn: "袖子",   py: "xiùzi",       en: "Sleeve",
    example: { cn: "袖子长度不对。", py: "Xiùzi chángdù bù duì.", en: "The sleeve length is wrong." }},
  { id: 26, cat: "parts", cn: "袖口",   py: "xiùkǒu",      en: "Cuff",
    example: { cn: "袖口要缝纽扣。", py: "Xiùkǒu yào féng niǔkòu.", en: "Buttons need to be sewn on the cuff." }},
  { id: 27, cat: "parts", cn: "下摆",   py: "xiàbǎi",      en: "Hem (bottom edge of garment)",
    example: { cn: "下摆要卷三折。", py: "Xiàbǎi yào juǎn sān zhé.", en: "The hem needs a triple fold." }},
  { id: 28, cat: "parts", cn: "前片",   py: "qián piàn",   en: "Front Panel / Front Body",
    example: { cn: "前片有口袋。", py: "Qián piàn yǒu kǒudài.", en: "The front panel has a pocket." }},
  { id: 29, cat: "parts", cn: "后片",   py: "hòu piàn",    en: "Back Panel / Back Body",
    example: { cn: "后片有开叉。", py: "Hòu piàn yǒu kāichā.", en: "The back panel has a vent." }},
  { id: 30, cat: "parts", cn: "肩缝",   py: "jiān féng",   en: "Shoulder Seam",
    example: { cn: "肩缝要对齐。", py: "Jiān féng yào duìqí.", en: "The shoulder seam must be aligned." }},
  { id: 31, cat: "parts", cn: "侧缝",   py: "cè féng",     en: "Side Seam",
    example: { cn: "侧缝要烫开。", py: "Cè féng yào tàng kāi.", en: "The side seam needs to be pressed open." }},
  { id: 32, cat: "parts", cn: "腰带",   py: "yāodài",      en: "Waistband",
    example: { cn: "腰带宽度是4cm。", py: "Yāodài kuāndù shì 4 cm.", en: "The waistband width is 4cm." }},
  { id: 33, cat: "parts", cn: "口袋",   py: "kǒudài",      en: "Pocket",
    example: { cn: "口袋位置不对。", py: "Kǒudài wèizhi bù duì.", en: "The pocket position is wrong." }},
  { id: 34, cat: "parts", cn: "挖袋",   py: "wādài",       en: "Welt Pocket",
    example: { cn: "挖袋要烫平整。", py: "Wādài yào tàng píngzhěng.", en: "The welt pocket must be ironed smooth." }},
  { id: 35, cat: "parts", cn: "拉链",   py: "lāliàn",      en: "Zipper",
    example: { cn: "拉链缝歪了。", py: "Lāliàn féng wāi le.", en: "The zipper was sewn crooked." }},
  { id: 36, cat: "parts", cn: "纽扣",   py: "niǔkòu",      en: "Button",
    example: { cn: "纽扣要锁紧。", py: "Niǔkòu yào suǒ jǐn.", en: "The button must be fastened tightly." }},
  { id: 37, cat: "parts", cn: "扣眼",   py: "kòuyǎn",      en: "Buttonhole",
    example: { cn: "扣眼大小要一致。", py: "Kòuyǎn dàxiǎo yào yīzhì.", en: "Buttonhole sizes must be consistent." }},
  { id: 38, cat: "parts", cn: "省道",   py: "shěngdào",    en: "Dart",
    example: { cn: "胸省要对称。", py: "Xiōng shěng yào duìchèn.", en: "The chest darts must be symmetrical." }},
  { id: 39, cat: "parts", cn: "褶子",   py: "zhězi",       en: "Pleat / Tuck",
    example: { cn: "前裤腰有两个褶子。", py: "Qián kù yāo yǒu liǎng gè zhězi.", en: "The front trouser waist has two pleats." }},
  { id: 40, cat: "parts", cn: "缝份",   py: "féngfèn",     en: "Seam Allowance",
    example: { cn: "缝份是1cm。", py: "Féngfèn shì 1 cm.", en: "The seam allowance is 1cm." }},
  { id: 41, cat: "parts", cn: "门襟",   py: "ménjīn",      en: "Button Placket / Front Fly",
    example: { cn: "门襟要熨平。", py: "Ménjīn yào yùn píng.", en: "The button placket must be ironed flat." }},
  { id: 42, cat: "parts", cn: "里布",   py: "lǐ bù",       en: "Lining",
    example: { cn: "里布要服帖。", py: "Lǐ bù yào fútie.", en: "The lining must lay flat." }},
  { id: 43, cat: "parts", cn: "开叉",   py: "kāichā",      en: "Vent / Slit",
    example: { cn: "裙子后面有开叉。", py: "Qúnzi hòumiàn yǒu kāichā.", en: "The skirt has a back vent." }},
  { id: 44, cat: "parts", cn: "松紧带", py: "sōngjǐndài",  en: "Elastic Band",
    example: { cn: "松紧带的松紧度要合适。", py: "Sōngjǐndài de sōngjǐn dù yào héshì.", en: "The elastic band tension must be appropriate." }},
  { id: 45, cat: "parts", cn: "贴边",   py: "tiēbiān",     en: "Facing",
    example: { cn: "领口贴边要熨服帖。", py: "Lǐngkǒu tiēbiān yào yùn fútie.", en: "The neckline facing must be ironed flat." }},
  { id: 46, cat: "parts", cn: "肩垫",   py: "jiāndiàn",    en: "Shoulder Pad",
    example: { cn: "这款要加肩垫。", py: "Zhè kuǎn yào jiā jiāndiàn.", en: "This style needs shoulder pads." }},
  { id: 47, cat: "parts", cn: "裤腿",   py: "kùtuǐ",       en: "Trouser Leg",
    example: { cn: "裤腿长度要一样。", py: "Kùtuǐ chángdù yào yīyàng.", en: "Trouser leg lengths must be the same." }},
  { id: 48, cat: "parts", cn: "裆缝",   py: "dàng féng",   en: "Crotch Seam",
    example: { cn: "裆缝要加固。", py: "Dàng féng yào jiāgù.", en: "The crotch seam needs reinforcement." }},
  { id: 49, cat: "parts", cn: "腰头",   py: "yāotóu",      en: "Waist (top of trousers/skirt)",
    example: { cn: "腰头宽度是3cm。", py: "Yāotóu kuāndù shì 3 cm.", en: "The waist width is 3cm." }},
  { id: 50, cat: "parts", cn: "吊带",   py: "diàodài",     en: "Strap / Suspender",
    example: { cn: "吊带要缝在肩缝上。", py: "Diàodài yào féng zài jiān féng shàng.", en: "The strap must be sewn at the shoulder seam." }},

  // ─────────────────────────────────────────────────────
  //  OPERATIONS & PROCESSES
  // ─────────────────────────────────────────────────────
  { id: 51, cat: "operations", cn: "裁剪",    py: "cáijiǎn",     en: "Cutting",
    example: { cn: "今天裁剪多少件？", py: "Jīntiān cáijiǎn duōshao jiàn?", en: "How many pieces are being cut today?" }},
  { id: 52, cat: "operations", cn: "车缝",    py: "chēféng",     en: "Sewing (industrial)",
    example: { cn: "车缝线迹要整齐。", py: "Chēféng xiànjì yào zhěngqí.", en: "Sewing stitches must be neat." }},
  { id: 53, cat: "operations", cn: "熨烫",    py: "yùntàng",     en: "Ironing / Pressing",
    example: { cn: "熨烫要均匀。", py: "Yùntàng yào jūnyún.", en: "Ironing must be even." }},
  { id: 54, cat: "operations", cn: "整烫",    py: "zhěngtàng",   en: "Final Pressing / Finishing Iron",
    example: { cn: "整烫要达到样衣标准。", py: "Zhěngtàng yào dádào yàngyī biāozhǔn.", en: "Final pressing must meet the sample standard." }},
  { id: 55, cat: "operations", cn: "铺布",    py: "pūbù",        en: "Fabric Spreading / Laying",
    example: { cn: "铺布要平整，不能有气泡。", py: "Pūbù yào píngzhěng, bù néng yǒu qìpào.", en: "Fabric spreading must be smooth, no bubbles." }},
  { id: 56, cat: "operations", cn: "排料",    py: "páiliào",     en: "Marker Making / Pattern Layout",
    example: { cn: "排料要节省面料。", py: "Páiliào yào jiéshěng miànliào.", en: "Marker making must save fabric." }},
  { id: 57, cat: "operations", cn: "扎包",    py: "zhābāo",      en: "Bundling (cut pieces)",
    example: { cn: "扎包后要贴标签。", py: "Zhābāo hòu yào tiē biāoqiān.", en: "After bundling, attach a label." }},
  { id: 58, cat: "operations", cn: "缝纫",    py: "féngrèn",     en: "Sewing / Stitching",
    example: { cn: "缝纫速度要稳定。", py: "Féngrèn sùdù yào wěndìng.", en: "Sewing speed must be steady." }},
  { id: 59, cat: "operations", cn: "锁眼",    py: "suǒ yǎn",     en: "Buttonhole Making",
    example: { cn: "锁眼的位置要准确。", py: "Suǒ yǎn de wèizhi yào zhǔnquè.", en: "Buttonhole positions must be accurate." }},
  { id: 60, cat: "operations", cn: "钉扣",    py: "dìng kòu",    en: "Button Attaching",
    example: { cn: "钉扣要牢固。", py: "Dìng kòu yào láogù.", en: "Button attaching must be secure." }},
  { id: 61, cat: "operations", cn: "绷缝",    py: "bēng féng",   en: "Cover Stitch / Coverstitch",
    example: { cn: "下摆用绷缝机。", py: "Xiàbǎi yòng bēng féng jī.", en: "Use a coverstitch machine for the hem." }},
  { id: 62, cat: "operations", cn: "包缝",    py: "bāo féng",    en: "Serging / Overlocking",
    example: { cn: "所有裁片都要包缝。", py: "Suǒyǒu cái piàn dōu yào bāo féng.", en: "All cut pieces need overlocking." }},
  { id: 63, cat: "operations", cn: "剪线头",  py: "jiǎn xiàntóu", en: "Thread Trimming",
    example: { cn: "成品要剪净线头。", py: "Chéngpǐn yào jiǎn jìng xiàntóu.", en: "All thread ends must be trimmed on finished goods." }},
  { id: 64, cat: "operations", cn: "返修",    py: "fǎnxiū",      en: "Repair / Rework",
    example: { cn: "不合格的要返修。", py: "Bù hégé de yào fǎnxiū.", en: "Non-conforming pieces must be repaired." }},
  { id: 65, cat: "operations", cn: "包装",    py: "bāozhuāng",   en: "Packing / Packaging",
    example: { cn: "包装前要检查。", py: "Bāozhuāng qián yào jiǎnchá.", en: "Inspect before packing." }},
  { id: 66, cat: "operations", cn: "折叠",    py: "zhédié",      en: "Folding",
    example: { cn: "折叠方式按样板。", py: "Zhédié fāngshì àn yàngbǎn.", en: "Fold according to the sample board." }},
  { id: 67, cat: "operations", cn: "放码",    py: "fàngmǎ",      en: "Grading (size scaling)",
    example: { cn: "放码要按规格表。", py: "Fàngmǎ yào àn guīgé biǎo.", en: "Grading must follow the spec sheet." }},
  { id: 68, cat: "operations", cn: "粘合",    py: "zhānhé",      en: "Fusing / Bonding (interlining)",
    example: { cn: "衬布要粘合好。", py: "Chèn bù yào zhānhé hǎo.", en: "The interfacing must be properly fused." }},
  { id: 69, cat: "operations", cn: "打样",    py: "dǎ yàng",     en: "Sample Making / Prototyping",
    example: { cn: "新款先打样确认。", py: "Xīn kuǎn xiān dǎ yàng quèrèn.", en: "New styles need a sample made for approval first." }},
  { id: 70, cat: "operations", cn: "洗水",    py: "xǐ shuǐ",     en: "Garment Washing / Laundering (process)",
    example: { cn: "这款要洗水处理。", py: "Zhè kuǎn yào xǐ shuǐ chǔlǐ.", en: "This style requires a wash treatment." }},
  { id: 71, cat: "operations", cn: "上领",    py: "shàng lǐng",  en: "Collar Attachment",
    example: { cn: "上领要对准中心线。", py: "Shàng lǐng yào duìzhǔn zhōngxīn xiàn.", en: "Collar attachment must align with the center line." }},
  { id: 72, cat: "operations", cn: "上袖",    py: "shàng xiù",   en: "Sleeve Setting",
    example: { cn: "上袖要均匀吃量。", py: "Shàng xiù yào jūnyún chī liàng.", en: "Sleeve setting must have even ease distribution." }},

  // ─────────────────────────────────────────────────────
  //  QUALITY CONTROL
  // ─────────────────────────────────────────────────────
  { id: 73, cat: "qc", cn: "质量",     py: "zhìliàng",     en: "Quality",
    example: { cn: "质量是第一位的。", py: "Zhìliàng shì dì yī wèi de.", en: "Quality is the top priority." }},
  { id: 74, cat: "qc", cn: "质检",     py: "zhìjiǎn",      en: "Quality Inspection / QC",
    example: { cn: "质检要全检。", py: "Zhìjiǎn yào quán jiǎn.", en: "QC requires a full inspection." }},
  { id: 75, cat: "qc", cn: "合格",     py: "hégé",         en: "Pass / Acceptable / Conforming",
    example: { cn: "这批合格，可以出货。", py: "Zhè pī hégé, kěyǐ chūhuò.", en: "This batch passes; it can be shipped." }},
  { id: 76, cat: "qc", cn: "不合格",   py: "bù hégé",      en: "Fail / Not Acceptable / Non-conforming",
    example: { cn: "这个不合格，退回去。", py: "Zhège bù hégé, tuì huíqù.", en: "This is not acceptable, send it back." }},
  { id: 77, cat: "qc", cn: "缺陷",     py: "quēxiàn",      en: "Defect",
    example: { cn: "这里有一个缺陷。", py: "Zhèlǐ yǒu yīgè quēxiàn.", en: "There is a defect here." }},
  { id: 78, cat: "qc", cn: "次品",     py: "cìpǐn",        en: "Defective / Second-grade Item",
    example: { cn: "次品要单独放。", py: "Cìpǐn yào dāndú fàng.", en: "Defective items must be placed separately." }},
  { id: 79, cat: "qc", cn: "色差",     py: "sèchā",        en: "Color Shading / Color Variation",
    example: { cn: "这两件有色差。", py: "Zhè liǎng jiàn yǒu sèchā.", en: "These two pieces have a color difference." }},
  { id: 80, cat: "qc", cn: "跳针",     py: "tiào zhēn",    en: "Skipped Stitch",
    example: { cn: "这里有跳针。", py: "Zhèlǐ yǒu tiào zhēn.", en: "There is a skipped stitch here." }},
  { id: 81, cat: "qc", cn: "断线",     py: "duàn xiàn",    en: "Broken Thread / Broken Stitch",
    example: { cn: "袖口有断线，要返修。", py: "Xiùkǒu yǒu duàn xiàn, yào fǎnxiū.", en: "The cuff has a broken stitch; it needs repair." }},
  { id: 82, cat: "qc", cn: "起球",     py: "qǐ qiú",       en: "Pilling",
    example: { cn: "这个面料容易起球。", py: "Zhège miànliào róngyì qǐ qiú.", en: "This fabric pills easily." }},
  { id: 83, cat: "qc", cn: "污渍",     py: "wūzì",         en: "Stain / Soiling",
    example: { cn: "这件有污渍，不合格。", py: "Zhè jiàn yǒu wūzì, bù hégé.", en: "This piece has a stain; it's not acceptable." }},
  { id: 84, cat: "qc", cn: "歪斜",     py: "wāixié",       en: "Skewed / Crooked / Off-grain",
    example: { cn: "这个缝线歪斜了。", py: "Zhège féng xiàn wāixié le.", en: "This stitch line is skewed." }},
  { id: 85, cat: "qc", cn: "起皱",     py: "qǐ zhòu",      en: "Puckering / Wrinkling",
    example: { cn: "缝线处有起皱。", py: "Féng xiàn chù yǒu qǐ zhòu.", en: "There is puckering at the stitch line." }},
  { id: 86, cat: "qc", cn: "样品",     py: "yàngpǐn",      en: "Sample / Reference Piece",
    example: { cn: "要和样品对比。", py: "Yào hé yàngpǐn duìbǐ.", en: "Compare with the sample." }},
  { id: 87, cat: "qc", cn: "规格",     py: "guīgé",        en: "Specification / Specs",
    example: { cn: "按规格表生产。", py: "Àn guīgé biǎo shēngchǎn.", en: "Produce according to the spec sheet." }},
  { id: 88, cat: "qc", cn: "测量",     py: "cèliáng",      en: "Measure / Measurement",
    example: { cn: "先测量尺寸。", py: "Xiān cèliáng chǐcùn.", en: "Measure the dimensions first." }},
  { id: 89, cat: "qc", cn: "公差",     py: "gōngchā",      en: "Tolerance",
    example: { cn: "公差是±0.5cm。", py: "Gōngchā shì ±0.5 cm.", en: "The tolerance is ±0.5cm." }},
  { id: 90, cat: "qc", cn: "抽检",     py: "chōujiǎn",     en: "Random / Spot Check",
    example: { cn: "今天要做抽检。", py: "Jīntiān yào zuò chōujiǎn.", en: "Today we're doing a spot check." }},
  { id: 91, cat: "qc", cn: "全检",     py: "quánjiǎn",     en: "Full / 100% Inspection",
    example: { cn: "出货前要全检。", py: "Chūhuò qián yào quánjiǎn.", en: "Do a full inspection before shipment." }},
  { id: 92, cat: "qc", cn: "破洞",     py: "pòdòng",       en: "Hole / Tear",
    example: { cn: "这件有破洞，不能出货。", py: "Zhè jiàn yǒu pòdòng, bù néng chūhuò.", en: "This has a hole; it can't be shipped." }},
  { id: 93, cat: "qc", cn: "线头",     py: "xiàntóu",      en: "Loose Thread End",
    example: { cn: "线头要剪干净。", py: "Xiàntóu yào jiǎn gānjìng.", en: "Thread ends must be trimmed clean." }},
  { id: 94, cat: "qc", cn: "对称",     py: "duìchèn",      en: "Symmetrical",
    example: { cn: "口袋要对称。", py: "Kǒudài yào duìchèn.", en: "Pockets must be symmetrical." }},

  // ─────────────────────────────────────────────────────
  //  EQUIPMENT & TOOLS
  // ─────────────────────────────────────────────────────
  { id: 95,  cat: "equipment", cn: "缝纫机",  py: "féngrèn jī",  en: "Sewing Machine",
    example: { cn: "缝纫机坏了。", py: "Féngrèn jī huài le.", en: "The sewing machine is broken." }},
  { id: 96,  cat: "equipment", cn: "熨斗",    py: "yùndǒu",      en: "Iron",
    example: { cn: "熨斗温度要调好。", py: "Yùndǒu wēndù yào tiáo hǎo.", en: "The iron temperature must be set correctly." }},
  { id: 97,  cat: "equipment", cn: "烫台",    py: "tàngtái",     en: "Ironing Board / Press Table",
    example: { cn: "烫台要平整。", py: "Tàngtái yào píngzhěng.", en: "The ironing board must be flat." }},
  { id: 98,  cat: "equipment", cn: "蒸汽熨斗", py: "zhēngqì yùndǒu", en: "Steam Iron",
    example: { cn: "用蒸汽熨斗烫领子。", py: "Yòng zhēngqì yùndǒu tàng lǐngzi.", en: "Use the steam iron to press the collar." }},
  { id: 99,  cat: "equipment", cn: "锁边机",  py: "suǒ biān jī", en: "Overlocker / Serger",
    example: { cn: "锁边机的线断了。", py: "Suǒ biān jī de xiàn duàn le.", en: "The serger thread has broken." }},
  { id: 100, cat: "equipment", cn: "锁眼机",  py: "suǒ yǎn jī",  en: "Buttonhole Machine",
    example: { cn: "锁眼机需要调节。", py: "Suǒ yǎn jī xūyào tiáojié.", en: "The buttonhole machine needs adjustment." }},
  { id: 101, cat: "equipment", cn: "钉扣机",  py: "dìng kòu jī", en: "Button Sewing Machine",
    example: { cn: "钉扣机线不够了。", py: "Dìng kòu jī xiàn bù gòu le.", en: "The button sewing machine is running out of thread." }},
  { id: 102, cat: "equipment", cn: "剪刀",    py: "jiǎndāo",     en: "Scissors",
    example: { cn: "剪刀要锋利。", py: "Jiǎndāo yào fēnglì.", en: "Scissors must be sharp." }},
  { id: 103, cat: "equipment", cn: "裁刀",    py: "cáidāo",      en: "Cutting Knife / Blade",
    example: { cn: "裁刀要换新的。", py: "Cáidāo yào huàn xīn de.", en: "The cutting blade needs to be replaced." }},
  { id: 104, cat: "equipment", cn: "针",       py: "zhēn",        en: "Needle",
    example: { cn: "换一根新针。", py: "Huàn yī gēn xīn zhēn.", en: "Change to a new needle." }},
  { id: 105, cat: "equipment", cn: "线",       py: "xiàn",        en: "Thread",
    example: { cn: "这个颜色的线没有了。", py: "Zhège yánsè de xiàn méiyǒu le.", en: "There's no more thread in this color." }},
  { id: 106, cat: "equipment", cn: "梭芯",    py: "suō xīn",     en: "Bobbin",
    example: { cn: "梭芯的线要换了。", py: "Suō xīn de xiàn yào huàn le.", en: "The bobbin thread needs to be changed." }},
  { id: 107, cat: "equipment", cn: "卷尺",    py: "juǎnchǐ",     en: "Measuring Tape",
    example: { cn: "用卷尺量长度。", py: "Yòng juǎnchǐ liáng chángdù.", en: "Use the measuring tape to measure the length." }},
  { id: 108, cat: "equipment", cn: "标尺",    py: "biāochǐ",     en: "Ruler / Scale",
    example: { cn: "用标尺画缝份线。", py: "Yòng biāochǐ huà féngfèn xiàn.", en: "Use the ruler to mark the seam allowance line." }},
  { id: 109, cat: "equipment", cn: "包装机",  py: "bāozhuāng jī", en: "Packing Machine",
    example: { cn: "包装机要校准。", py: "Bāozhuāng jī yào jiàozhǔn.", en: "The packing machine needs calibration." }},
  { id: 110, cat: "equipment", cn: "粘合机",  py: "zhānhé jī",   en: "Fusing Press Machine",
    example: { cn: "粘合机温度要检查。", py: "Zhānhé jī wēndù yào jiǎnchá.", en: "Check the fusing machine temperature." }},

  // ─────────────────────────────────────────────────────
  //  PEOPLE & ROLES
  // ─────────────────────────────────────────────────────
  { id: 111, cat: "roles", cn: "组长",     py: "zǔzhǎng",     en: "Team Leader / Supervisor",
    example: { cn: "组长说要重做。", py: "Zǔzhǎng shuō yào chóngzuò.", en: "The team leader said to redo it." }},
  { id: 112, cat: "roles", cn: "线长",     py: "xiànzhǎng",   en: "Line Supervisor",
    example: { cn: "有问题找线长。", py: "Yǒu wèntí zhǎo xiànzhǎng.", en: "If there's a problem, find the line supervisor." }},
  { id: 113, cat: "roles", cn: "主任",     py: "zhǔrèn",      en: "Manager / Director (dept.)",
    example: { cn: "主任来检查了。", py: "Zhǔrèn lái jiǎnchá le.", en: "The manager has come to inspect." }},
  { id: 114, cat: "roles", cn: "经理",     py: "jīnglǐ",      en: "Manager",
    example: { cn: "经理要见你。", py: "Jīnglǐ yào jiàn nǐ.", en: "The manager wants to see you." }},
  { id: 115, cat: "roles", cn: "工人",     py: "gōngrén",     en: "Worker",
    example: { cn: "工人要听从指导。", py: "Gōngrén yào tīngcóng zhǐdǎo.", en: "Workers must follow instructions." }},
  { id: 116, cat: "roles", cn: "技术员",   py: "jìshùyuán",   en: "Technician",
    example: { cn: "找技术员来修机器。", py: "Zhǎo jìshùyuán lái xiū jīqì.", en: "Get the technician to fix the machine." }},
  { id: 117, cat: "roles", cn: "版师",     py: "bǎnshī",      en: "Pattern Maker",
    example: { cn: "版师在改板型。", py: "Bǎnshī zài gǎi bǎn xíng.", en: "The pattern maker is modifying the pattern." }},
  { id: 118, cat: "roles", cn: "跟单",     py: "gēndān",      en: "Merchandiser / Order Follower",
    example: { cn: "跟单说交期要提前。", py: "Gēndān shuō jiāoqī yào tíqián.", en: "The merchandiser said the delivery deadline is moved up." }},
  { id: 119, cat: "roles", cn: "质检员",   py: "zhìjiǎnyuán", en: "Quality Inspector",
    example: { cn: "质检员说有问题。", py: "Zhìjiǎnyuán shuō yǒu wèntí.", en: "The quality inspector said there is a problem." }},
  { id: 120, cat: "roles", cn: "裁床师",   py: "cái chuáng shī", en: "Cutter / Cutting Operator",
    example: { cn: "裁床师在排料。", py: "Cái chuáng shī zài páiliào.", en: "The cutter is laying the marker." }},

  // ─────────────────────────────────────────────────────
  //  GARMENT TYPES
  // ─────────────────────────────────────────────────────
  { id: 121, cat: "garments", cn: "衬衫",    py: "chènshān",    en: "Shirt / Blouse",
    example: { cn: "这批衬衫多少件？", py: "Zhè pī chènshān duōshao jiàn?", en: "How many pieces are in this shirt batch?" }},
  { id: 122, cat: "garments", cn: "裤子",    py: "kùzi",        en: "Trousers / Pants",
    example: { cn: "裤子的裤腿要对齐。", py: "Kùzi de kùtuǐ yào duìqí.", en: "The trouser legs must be aligned." }},
  { id: 123, cat: "garments", cn: "牛仔裤",  py: "niúzǎikù",    en: "Jeans",
    example: { cn: "这批牛仔裤要洗水。", py: "Zhè pī niúzǎikù yào xǐ shuǐ.", en: "This batch of jeans needs to be washed." }},
  { id: 124, cat: "garments", cn: "T恤",     py: "T xù",        en: "T-shirt",
    example: { cn: "T恤的领口要对称。", py: "T xù de lǐngkǒu yào duìchèn.", en: "The T-shirt neckline must be symmetrical." }},
  { id: 125, cat: "garments", cn: "夹克",    py: "jiákè",       en: "Jacket",
    example: { cn: "这款夹克有拉链。", py: "Zhè kuǎn jiákè yǒu lāliàn.", en: "This jacket style has a zipper." }},
  { id: 126, cat: "garments", cn: "外套",    py: "wàitào",      en: "Coat / Outerwear",
    example: { cn: "外套要加里布。", py: "Wàitào yào jiā lǐ bù.", en: "The coat needs lining." }},
  { id: 127, cat: "garments", cn: "连衣裙",  py: "liányīqún",   en: "Dress",
    example: { cn: "连衣裙的拉链在哪里？", py: "Liányīqún de lāliàn zài nǎlǐ?", en: "Where is the zipper on the dress?" }},
  { id: 128, cat: "garments", cn: "裙子",    py: "qúnzi",       en: "Skirt",
    example: { cn: "裙子长度按规格表。", py: "Qúnzi chángdù àn guīgé biǎo.", en: "Skirt length follows the spec sheet." }},
  { id: 129, cat: "garments", cn: "西装",    py: "xīzhuāng",    en: "Suit",
    example: { cn: "西装要精工细作。", py: "Xīzhuāng yào jīnggōng xì zuò.", en: "Suits require fine craftsmanship." }},
  { id: 130, cat: "garments", cn: "运动服",  py: "yùndòngfú",   en: "Sportswear / Activewear",
    example: { cn: "运动服用弹力面料。", py: "Yùndòngfú yòng tánlì miànliào.", en: "Sportswear uses stretch fabric." }},
  { id: 131, cat: "garments", cn: "内衣",    py: "nèiyī",       en: "Underwear / Lingerie",
    example: { cn: "内衣车缝要细腻。", py: "Nèiyī chēféng yào xìnì.", en: "Underwear sewing must be delicate." }},
  { id: 132, cat: "garments", cn: "童装",    py: "tóngzhuāng",  en: "Children's Clothing",
    example: { cn: "童装要检查安全标准。", py: "Tóngzhuāng yào jiǎnchá ānquán biāozhǔn.", en: "Children's clothing must meet safety standards." }},
  { id: 133, cat: "garments", cn: "工作服",  py: "gōngzuòfú",   en: "Workwear / Uniform",
    example: { cn: "工作服要耐磨。", py: "Gōngzuòfú yào nài mó.", en: "Workwear must be wear-resistant." }},

  // ─────────────────────────────────────────────────────
  //  SIZES, COLORS & SPECS
  // ─────────────────────────────────────────────────────
  { id: 134, cat: "sizes", cn: "尺寸",    py: "chǐcùn",      en: "Measurement / Size / Dimension",
    example: { cn: "尺寸不对，要重新量。", py: "Chǐcùn bù duì, yào chóngxīn liáng.", en: "The measurement is wrong; re-measure." }},
  { id: 135, cat: "sizes", cn: "颜色",    py: "yánsè",       en: "Color",
    example: { cn: "这个颜色不对。", py: "Zhège yánsè bù duì.", en: "This color is wrong." }},
  { id: 136, cat: "sizes", cn: "黑色",    py: "hēisè",       en: "Black",
    example: { cn: "这款有黑色吗？", py: "Zhè kuǎn yǒu hēisè ma?", en: "Is this style available in black?" }},
  { id: 137, cat: "sizes", cn: "白色",    py: "báisè",       en: "White",
    example: { cn: "白色要特别注意污渍。", py: "Báisè yào tèbié zhùyì wūzì.", en: "Be especially careful about stains on white." }},
  { id: 138, cat: "sizes", cn: "蓝色",    py: "lánsè",       en: "Blue",
    example: { cn: "蓝色系列有三个颜色。", py: "Lánsè xìliè yǒu sān gè yánsè.", en: "The blue series has three colors." }},
  { id: 139, cat: "sizes", cn: "红色",    py: "hóngsè",      en: "Red",
    example: { cn: "红色很容易褪色。", py: "Hóngsè hěn róngyì tuìsè.", en: "Red fades easily." }},
  { id: 140, cat: "sizes", cn: "号",      py: "hào",         en: "Size (number/designation)",
    example: { cn: "这个是什么号？", py: "Zhège shì shénme hào?", en: "What size is this?" }},
  { id: 141, cat: "sizes", cn: "胸围",    py: "xiōngwéi",    en: "Chest Circumference / Bust",
    example: { cn: "胸围差了两厘米。", py: "Xiōngwéi chà le liǎng lí mǐ.", en: "The chest measurement is off by 2cm." }},
  { id: 142, cat: "sizes", cn: "腰围",    py: "yāowéi",      en: "Waist Circumference",
    example: { cn: "腰围按规格表是76cm。", py: "Yāowéi àn guīgé biǎo shì 76 cm.", en: "The waist per the spec sheet is 76cm." }},
  { id: 143, cat: "sizes", cn: "臀围",    py: "túnwéi",      en: "Hip Circumference",
    example: { cn: "臀围量对了吗？", py: "Túnwéi liáng duì le ma?", en: "Did you measure the hip correctly?" }},
  { id: 144, cat: "sizes", cn: "衣长",    py: "yī cháng",    en: "Garment Length",
    example: { cn: "衣长要比样品短1cm。", py: "Yī cháng yào bǐ yàngpǐn duǎn 1 cm.", en: "The garment length should be 1cm shorter than the sample." }},
  { id: 145, cat: "sizes", cn: "袖长",    py: "xiù cháng",   en: "Sleeve Length",
    example: { cn: "袖长62cm是哪个号？", py: "Xiù cháng 62 cm shì nǎ gè hào?", en: "Which size has a sleeve length of 62cm?" }},
  { id: 146, cat: "sizes", cn: "厘米",    py: "lí mǐ",       en: "Centimeter (cm)",
    example: { cn: "差了0.5厘米。", py: "Chà le 0.5 lí mǐ.", en: "It's off by 0.5 centimeters." }},
  { id: 147, cat: "sizes", cn: "克重",    py: "kè zhòng",    en: "Fabric Weight (GSM / grams)",
    example: { cn: "这个面料克重多少？", py: "Zhège miànliào kè zhòng duōshao?", en: "What is the fabric weight (GSM)?" }},

  // ─────────────────────────────────────────────────────
  //  FACTORY & PRODUCTION
  // ─────────────────────────────────────────────────────
  { id: 148, cat: "factory", cn: "产量",    py: "chǎnliàng",   en: "Output / Production Volume",
    example: { cn: "今天的产量是多少？", py: "Jīntiān de chǎnliàng shì duōshao?", en: "What is today's output?" }},
  { id: 149, cat: "factory", cn: "目标",    py: "mùbiāo",      en: "Target / Goal",
    example: { cn: "今天的目标是500件。", py: "Jīntiān de mùbiāo shì 500 jiàn.", en: "Today's target is 500 pieces." }},
  { id: 150, cat: "factory", cn: "生产线",  py: "shēngchǎn xiàn", en: "Production Line",
    example: { cn: "第三生产线效率最高。", py: "Dì sān shēngchǎn xiàn xiàolǜ zuì gāo.", en: "The third production line has the highest efficiency." }},
  { id: 151, cat: "factory", cn: "加班",    py: "jiābān",      en: "Overtime / Work Overtime",
    example: { cn: "今天要加班吗？", py: "Jīntiān yào jiābān ma?", en: "Do we have overtime today?" }},
  { id: 152, cat: "factory", cn: "交货期",  py: "jiāohuòqī",   en: "Delivery Deadline",
    example: { cn: "交货期是下周五。", py: "Jiāohuòqī shì xià zhōuwǔ.", en: "The delivery deadline is next Friday." }},
  { id: 153, cat: "factory", cn: "订单",    py: "dìngdān",     en: "Order",
    example: { cn: "这个订单多少件？", py: "Zhège dìngdān duōshao jiàn?", en: "How many pieces is this order?" }},
  { id: 154, cat: "factory", cn: "批次",    py: "pīcì",        en: "Batch / Lot",
    example: { cn: "这个批次有问题。", py: "Zhège pīcì yǒu wèntí.", en: "There's a problem with this batch." }},
  { id: 155, cat: "factory", cn: "出货",    py: "chūhuò",      en: "Shipment / Ship Out",
    example: { cn: "什么时候出货？", py: "Shénme shíhòu chūhuò?", en: "When is the shipment?" }},
  { id: 156, cat: "factory", cn: "成品",    py: "chéngpǐn",    en: "Finished Product",
    example: { cn: "成品放在仓库。", py: "Chéngpǐn fàng zài cāngkù.", en: "Put finished goods in the warehouse." }},
  { id: 157, cat: "factory", cn: "半成品",  py: "bànchéngpǐn", en: "Semi-finished / Work in Progress",
    example: { cn: "半成品堆积太多了。", py: "Bànchéngpǐn duījī tài duō le.", en: "There are too many semi-finished goods piling up." }},
  { id: 158, cat: "factory", cn: "效率",    py: "xiàolǜ",      en: "Efficiency",
    example: { cn: "今天效率不高。", py: "Jīntiān xiàolǜ bù gāo.", en: "Today's efficiency is not high." }},
  { id: 159, cat: "factory", cn: "白班",    py: "báibān",      en: "Day Shift",
    example: { cn: "我上白班。", py: "Wǒ shàng báibān.", en: "I'm on the day shift." }},
  { id: 160, cat: "factory", cn: "夜班",    py: "yèbān",       en: "Night Shift",
    example: { cn: "今晚要上夜班。", py: "Jīnwǎn yào shàng yèbān.", en: "We're on the night shift tonight." }},
  { id: 161, cat: "factory", cn: "休息",    py: "xiūxi",       en: "Break / Rest",
    example: { cn: "休息10分钟。", py: "Xiūxi 10 fēnzhōng.", en: "10-minute break." }},
  { id: 162, cat: "factory", cn: "仓库",    py: "cāngkù",      en: "Warehouse / Storage",
    example: { cn: "物料在仓库里。", py: "Wùliào zài cāngkù lǐ.", en: "Materials are in the warehouse." }},
  { id: 163, cat: "factory", cn: "领料",    py: "lǐng liào",   en: "Collect / Request Materials",
    example: { cn: "去仓库领料。", py: "Qù cāngkù lǐng liào.", en: "Go to the warehouse to collect materials." }},
  { id: 164, cat: "factory", cn: "物料",    py: "wùliào",      en: "Materials / Supplies",
    example: { cn: "物料不够用了。", py: "Wùliào bù gòu yòng le.", en: "We're running out of materials." }},

  // ─────────────────────────────────────────────────────
  //  WORKPLACE SURVIVAL
  // ─────────────────────────────────────────────────────
  { id: 165, cat: "workplace", cn: "你好",    py: "nǐ hǎo",      en: "Hello",
    example: { cn: "你好，我是新来的工人。", py: "Nǐ hǎo, wǒ shì xīn lái de gōngrén.", en: "Hello, I'm a new worker." }},
  { id: 166, cat: "workplace", cn: "早上好",  py: "zǎoshang hǎo", en: "Good morning",
    example: { cn: "早上好，组长！", py: "Zǎoshang hǎo, zǔzhǎng!", en: "Good morning, team leader!" }},
  { id: 167, cat: "workplace", cn: "谢谢",    py: "xièxiè",      en: "Thank you",
    example: { cn: "谢谢你的帮助。", py: "Xièxiè nǐ de bāngzhù.", en: "Thank you for your help." }},
  { id: 168, cat: "workplace", cn: "对不起",  py: "duìbuqǐ",     en: "Sorry / I apologize",
    example: { cn: "对不起，我做错了。", py: "Duìbuqǐ, wǒ zuò cuò le.", en: "Sorry, I made a mistake." }},
  { id: 169, cat: "workplace", cn: "我不懂",  py: "wǒ bù dǒng",  en: "I don't understand",
    example: { cn: "对不起，我不懂，请再说一遍。", py: "Duìbuqǐ, wǒ bù dǒng, qǐng zài shuō yībiàn.", en: "Sorry, I don't understand, please say it again." }},
  { id: 170, cat: "workplace", cn: "请再说一遍", py: "qǐng zài shuō yībiàn", en: "Please say it again",
    example: { cn: "我没听清楚，请再说一遍。", py: "Wǒ méi tīng qīngchǔ, qǐng zài shuō yībiàn.", en: "I didn't hear clearly, please say it again." }},
  { id: 171, cat: "workplace", cn: "慢一点",  py: "màn yīdiǎn",  en: "Slower please / Slow down",
    example: { cn: "你说慢一点，我听不懂。", py: "Nǐ shuō màn yīdiǎn, wǒ tīng bù dǒng.", en: "Please speak slower; I can't follow." }},
  { id: 172, cat: "workplace", cn: "怎么做",  py: "zěnme zuò",   en: "How to do it?",
    example: { cn: "这个工序怎么做？", py: "Zhège gōngxù zěnme zuò?", en: "How is this operation done?" }},
  { cn: "辛苦了",  py: "xīnkǔ le",   en: "You've worked hard / Good job", cat: "workplace", id: 173,
    example: { cn: "今天大家辛苦了！", py: "Jīntiān dàjiā xīnkǔ le!", en: "Everyone worked hard today!" }},
  { id: 174, cat: "workplace", cn: "停机",    py: "tíng jī",     en: "Stop the machine",
    example: { cn: "马上停机！", py: "Mǎshàng tíng jī!", en: "Stop the machine immediately!" }},
  { id: 175, cat: "workplace", cn: "机器坏了", py: "jīqì huài le", en: "The machine is broken",
    example: { cn: "我的机器坏了，怎么办？", py: "Wǒ de jīqì huài le, zěnme bàn?", en: "My machine is broken; what do I do?" }},
  { id: 176, cat: "workplace", cn: "我需要帮助", py: "wǒ xūyào bāngzhù", en: "I need help",
    example: { cn: "请问，我需要帮助。", py: "Qǐngwèn, wǒ xūyào bāngzhù.", en: "Excuse me, I need help." }},
  { id: 177, cat: "workplace", cn: "厕所在哪里", py: "cèsuǒ zài nǎlǐ", en: "Where is the toilet?",
    example: { cn: "不好意思，厕所在哪里？", py: "Bùhǎoyìsi, cèsuǒ zài nǎlǐ?", en: "Excuse me, where is the toilet?" }},
  { id: 178, cat: "workplace", cn: "我受伤了", py: "wǒ shòushāng le", en: "I am injured",
    example: { cn: "我受伤了，需要帮助！", py: "Wǒ shòushāng le, xūyào bāngzhù!", en: "I am injured; I need help!" }},
];

// ─────────────────────────────────────────────────────────────────────────────
//  PHRASEBOOK
// ─────────────────────────────────────────────────────────────────────────────
const PHRASEBOOK = [
  // Daily Work
  { cat: "daily",    cn: "今天的任务是什么？",         py: "Jīntiān de rènwù shì shénme?",          en: "What is today's task?",             situation: "Start of shift" },
  { cat: "daily",    cn: "产量达标了吗？",              py: "Chǎnliàng dá biāo le ma?",              en: "Have we reached the production target?", situation: "Checking progress" },
  { cat: "daily",    cn: "今天加班到几点？",            py: "Jīntiān jiābān dào jǐ diǎn?",          en: "What time does overtime go until today?", situation: "Overtime inquiry" },
  { cat: "daily",    cn: "这批货什么时候出货？",        py: "Zhè pī huò shénme shíhòu chūhuò?",      en: "When does this batch ship out?",     situation: "Delivery inquiry" },
  { cat: "daily",    cn: "我去领料。",                  py: "Wǒ qù lǐng liào.",                      en: "I'm going to get materials.",        situation: "Getting supplies" },
  { cat: "daily",    cn: "线用完了。",                  py: "Xiàn yòng wán le.",                     en: "The thread has run out.",            situation: "Requesting supplies" },
  { cat: "daily",    cn: "这个款式的样品在哪里？",      py: "Zhège kuǎnshì de yàngpǐn zài nǎlǐ?",   en: "Where is the sample for this style?", situation: "Looking for reference" },

  // Quality issues
  { cat: "quality",  cn: "这件不合格，要返修。",        py: "Zhè jiàn bù hégé, yào fǎnxiū.",        en: "This piece fails; it needs repair.",  situation: "QC rejection" },
  { cat: "quality",  cn: "这里有色差，换批次。",        py: "Zhèlǐ yǒu sèchā, huàn pīcì.",          en: "There's a color difference here; change the batch.", situation: "Color issue" },
  { cat: "quality",  cn: "尺寸不对，请重新量。",        py: "Chǐcùn bù duì, qǐng chóngxīn liáng.", en: "The measurement is wrong; please re-measure.", situation: "Measurement issue" },
  { cat: "quality",  cn: "这件和样品不一样。",          py: "Zhè jiàn hé yàngpǐn bù yīyàng.",        en: "This piece doesn't match the sample.", situation: "Sample discrepancy" },
  { cat: "quality",  cn: "缝线有问题，请检查。",        py: "Féng xiàn yǒu wèntí, qǐng jiǎnchá.",   en: "There's a problem with the stitch; please check.", situation: "Stitching issue" },
  { cat: "quality",  cn: "这批线头没有剪干净。",        py: "Zhè pī xiàntóu méiyǒu jiǎn gānjìng.",  en: "The thread ends on this batch aren't trimmed cleanly.", situation: "Finishing issue" },
  { cat: "quality",  cn: "按样品重新做。",              py: "Àn yàngpǐn chóngxīn zuò.",             en: "Redo it according to the sample.",    situation: "Rework instruction" },
  { cat: "quality",  cn: "公差是多少？",                py: "Gōngchā shì duōshao?",                 en: "What is the tolerance?",             situation: "Asking for specs" },

  // Machine & Equipment
  { cat: "machine",  cn: "我的机器出问题了，麻烦帮看一下。", py: "Wǒ de jīqì chū wèntí le, máfan bāng kàn yīxià.", en: "My machine has an issue; please take a look.", situation: "Machine trouble" },
  { cat: "machine",  cn: "针断了，怎么换？",            py: "Zhēn duàn le, zěnme huàn?",            en: "The needle broke; how do I change it?", situation: "Needle change" },
  { cat: "machine",  cn: "线跑了，帮我穿一下。",        py: "Xiàn pǎo le, bāng wǒ chuān yīxià.",    en: "The thread came out; help me thread it.", situation: "Re-threading" },
  { cat: "machine",  cn: "熨斗温度调多少度？",          py: "Yùndǒu wēndù tiáo duōshao dù?",        en: "What temperature should I set the iron?", situation: "Iron setting" },
  { cat: "machine",  cn: "蒸汽不够了。",                py: "Zhēngqì bù gòu le.",                   en: "The steam isn't enough.",            situation: "Steam issue" },

  // Communication & Directions
  { cat: "comms",    cn: "我是新来的，请多指教。",      py: "Wǒ shì xīn lái de, qǐng duō zhǐjiào.", en: "I'm new here; please guide me.",     situation: "First day" },
  { cat: "comms",    cn: "请用慢一点说，我在学中文。",  py: "Qǐng yòng màn yīdiǎn shuō, wǒ zài xué zhōngwén.", en: "Please speak more slowly; I'm learning Chinese.", situation: "Language barrier" },
  { cat: "comms",    cn: "这个中文怎么说？",            py: "Zhège zhōngwén zěnme shuō?",           en: "How do you say this in Chinese?",    situation: "Learning vocab" },
  { cat: "comms",    cn: "我明白了，谢谢！",            py: "Wǒ míngbái le, xièxiè!",              en: "I understand now, thank you!",       situation: "Confirmation" },
  { cat: "comms",    cn: "能再示范一次吗？",            py: "Néng zài shìfàn yīcì ma?",             en: "Can you demonstrate it one more time?", situation: "Asking for demo" },
  { cat: "comms",    cn: "这个放在哪里？",              py: "Zhège fàng zài nǎlǐ?",                en: "Where does this go?",               situation: "Organization" },
  { cat: "comms",    cn: "做完了，接下来做什么？",      py: "Zuò wán le, jiēxiàlái zuò shénme?",    en: "Done! What should I do next?",      situation: "Next task" },
];

const PHRASE_CATEGORIES = [
  { id: "daily",   label: "Daily Work",         emoji: "📋" },
  { id: "quality", label: "Quality Issues",     emoji: "🔍" },
  { id: "machine", label: "Machine & Equipment",emoji: "⚙️" },
  { id: "comms",   label: "Communication",      emoji: "💬" },
];
